In [ ]:
# I realize there are probably easier ways to do what I did, but this worked for me.

In [1]:
import pandas as pd
import numpy as np
import pybaseball
import matplotlib as plt
from pybaseball import statcast
from pybaseball import statcast_pitcher
from pybaseball import playerid_lookup
from pybaseball import pitching_stats_range
#import packages

In [14]:
pstpitchdata = pitching_stats_range('2021-06-20','2021-10-31')
pstpitchdata.columns
pstpitchdata
#get basic data after June 20th

,Name,Age,#days,Lev,Tm,G,GS,W,L,SV,...,Str,StL,StS,GB/FB,LD,PU,WHIP,BAbip,SO9,SO/W
1,Fernando Abad,35,9,Maj-AL,Baltimore,16,0,NaN,NaN,NaN,...,0.61,0.17,0.06,0.49,0.26,0.06,1.698,0.344,5.1,1.43
2,Cory Abbott,25,9,Maj-NL,Chicago,3,1,NaN,NaN,NaN,...,0.59,0.14,0.06,0.38,0.28,0.03,2.000,0.259,6.0,1.00
3,Albert Abreu,25,9,Maj-AL,New York,24,0,2.0,NaN,1.0,...,0.61,0.16,0.10,0.44,0.25,0.05,1.429,0.243,8.0,1.67
4,Bryan Abreu,24,42,Maj-AL,Houston,10,0,1.0,NaN,NaN,...,0.59,0.14,0.14,0.41,0.29,0.06,1.839,0.394,11.3,2.60
5,Domingo Acevedo,27,7,Maj-AL,Oakland,10,0,NaN,NaN,NaN,...,0.66,0.11,0.14,0.42,0.16,0.06,1.182,0.214,7.4,2.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822,Alex Young,27,28,"Maj-AL,Maj-NL","Cleveland,Arizona",13,1,NaN,2.0,NaN,...,0.61,0.13,0.09,0.46,0.26,0.04,2.431,0.411,5.1,1.00
823,Angel Zerpa,21,10,Maj-AL,Kansas City,1,1,NaN,1.0,NaN,...,0.65,0.21,0.04,0.47,0.33,0.00,0.800,0.214,7.2,4.00
824,Kyle Zimmer,29,8,Maj-AL,Kansas City,29,1,1.0,1.0,NaN,...,0.58,0.15,0.10,0.52,0.16,0.06,1.866,0.316,6.3,0.95
825,Bruce Zimmermann,26,7,Maj-AL,Baltimore,2,2,NaN,1.0,NaN,...,0.63,0.16,0.06,0.33,0.22,0.06,1.929,0.313,5.8,1.50
826,Tyler Zuber,26,10,Maj-AL,Kansas City,11,0,NaN,1.0,NaN,...,0.66,0.14,0.09,0.42,0.30,0.09,1.355,0.300,7.8,4.50

In [15]:
prepitchdata = pitching_stats_range('2021-04-01','2021-06-20')
#Get basic data before June 20th
prepitchdata

,Name,Age,#days,Lev,Tm,G,GS,W,L,SV,...,Str,StL,StS,GB/FB,LD,PU,WHIP,BAbip,SO9,SO/W
1,Cory Abbott,25,113,Maj-NL,Chicago,4,0,NaN,NaN,NaN,...,0.56,0.11,0.09,0.39,0.11,0.18,1.560,0.250,6.5,1.20
2,Albert Abreu,25,134,Maj-AL,New York,4,0,NaN,NaN,NaN,...,0.61,0.20,0.14,0.50,0.11,0.06,0.692,0.059,10.4,2.50
3,Bryan Abreu,24,137,Maj-AL,Houston,21,0,2.0,3.0,1.0,...,0.59,0.13,0.13,0.51,0.14,0.09,1.325,0.269,8.1,1.77
4,Jason Adam,29,154,Maj-NL,Chicago,9,0,NaN,NaN,NaN,...,0.53,0.13,0.13,0.33,0.33,0.17,1.957,0.471,15.3,2.17
5,Austin Adams,30,114,Maj-NL,San Diego,31,0,2.0,1.0,NaN,...,0.61,0.20,0.14,0.40,0.21,0.06,0.960,0.267,13.7,3.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,T.J. Zeuch,25,115,Maj-AL,Toronto,5,3,NaN,2.0,NaN,...,0.63,0.15,0.07,0.49,0.16,0.04,2.000,0.294,4.8,0.89
706,Kyle Zimmer,29,112,Maj-AL,Kansas City,24,1,3.0,NaN,2.0,...,0.62,0.17,0.11,0.52,0.16,0.03,0.940,0.226,9.1,2.55
707,Bruce Zimmermann,26,119,Maj-AL,Baltimore,12,11,4.0,4.0,NaN,...,0.63,0.17,0.11,0.42,0.28,0.08,1.475,0.322,8.0,2.65
708,Jordan Zimmermann,35,156,Maj-NL,Milwaukee,2,0,NaN,NaN,NaN,...,0.61,0.11,0.02,0.52,0.22,0.00,1.765,0.318,0.0,0.00
709,Tyler Zuber,26,128,Maj-AL,Kansas City,20,0,NaN,2.0,NaN,...,0.56,0.15,0.11,0.28,0.26,0.15,1.706,0.250,8.5,1.07

In [4]:
data = statcast(start_dt='2021-06-20', end_dt='2021-10-31')
#Statcast after June 20th

This is a large query, it may take a moment to complete

100%|████████████████████████████████████████████████████████████████████████████████| 134/134 [00:38<00:00,  3.48it/s]

In [5]:
preban_data = statcast(start_dt='2021-03-24', end_dt='2021-06-20')
#Statcast before June 20th

This is a large query, it may take a moment to complete

100%|██████████████████████████████████████████████████████████████████████████████████| 89/89 [00:15<00:00,  5.87it/s]

In [6]:
data

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment,spin_axis,delta_home_win_exp,delta_run_exp
490,FF,2021-10-10,99.2,-1.42,5.92,"Hendriks, Liam",514888,521230,strikeout,called_strike,...,12,6,12,6,12,Standard,Standard,201,0.0,-0.061
501,SL,2021-10-10,89.6,-1.49,5.8,"Hendriks, Liam",514888,521230,None,swinging_strike,...,12,6,12,6,12,Standard,Standard,136,0.0,-0.024
524,SL,2021-10-10,89.8,-1.68,5.84,"Hendriks, Liam",514888,521230,None,swinging_strike,...,12,6,12,6,12,Standard,Standard,178,0.0,-0.018
557,FF,2021-10-10,99.0,-1.45,5.92,"Hendriks, Liam",488771,521230,strikeout,swinging_strike,...,12,6,12,6,12,Strategic,Standard,196,0.001,-0.212
590,FF,2021-10-10,99.1,-1.48,5.86,"Hendriks, Liam",488771,521230,None,ball,...,12,6,12,6,12,Strategic,Standard,200,0.0,0.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4430,SI,2021-06-20,93.4,1.94,6.5,"Hentges, Sam",624428,656529,None,ball,...,0,0,0,0,0,Standard,Standard,145,0.0,0.038
3946,SI,2021-06-20,93.3,-2.64,6.06,"Brubaker, JT",656252,664141,field_out,hit_into_play,...,0,0,0,0,0,Infield shift,Standard,216,0.01,-0.103
4170,SI,2021-06-20,92.8,-2.58,6.08,"Brubaker, JT",642708,664141,field_out,hit_into_play,...,0,0,0,0,0,Standard,Standard,219,0.015,-0.136
4289,FF,2021-06-20,92.3,-2.44,6.14,"Brubaker, JT",642708,664141,None,called_strike,...,0,0,0,0,0,Standard,Standard,216,0.0,-0.027
4451,SI,2021-06-20,92.6,-2.69,6.07,"Brubaker, JT",514917,664141,field_out,hit_into_play,...,0,0,0,0,0,Standard,Standard,217,0.022,-0.241

In [7]:
preban_data

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment,spin_axis,delta_home_win_exp,delta_run_exp
2724,CU,2021-06-20,79.1,-1.17,5.5,"Chatwood, Tyler",596748,543022,field_out,hit_into_play,...,7,7,4,4,7,Standard,Standard,50,-0.015,-0.247
2791,FC,2021-06-20,89.7,-1.28,5.45,"Chatwood, Tyler",596748,543022,None,foul,...,7,7,4,4,7,Standard,Standard,108,-0.015,-0.094
2873,FC,2021-06-20,88.6,-1.25,5.45,"Chatwood, Tyler",596748,543022,None,called_strike,...,7,7,4,4,7,Standard,Standard,100,-0.015,-0.039
2963,SI,2021-06-20,95.9,-0.99,5.47,"Chatwood, Tyler",596748,543022,None,ball,...,7,7,4,4,7,Standard,Standard,200,-0.015,0.011
3043,CH,2021-06-20,89.2,-1.21,5.41,"Chatwood, Tyler",520471,543022,field_out,hit_into_play,...,7,7,4,4,7,Standard,Standard,211,-0.031,-0.172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3488,FF,2021-04-01,95.9,-1.92,6.15,"Márquez, Germán",605141,608566,None,called_strike,...,0,0,0,0,0,Standard,Standard,212,0.0,-0.078
3666,FF,2021-04-01,95.4,-1.66,6.17,"Márquez, Germán",605141,608566,None,ball,...,0,0,0,0,0,Strategic,Standard,<NA>,0.0,0.113
3727,FF,2021-04-01,96.1,-1.76,6.27,"Márquez, Germán",605141,608566,None,ball,...,0,0,0,0,0,Strategic,Standard,208,0.0,0.051
3986,FF,2021-04-01,95.6,-2.04,6.03,"Márquez, Germán",605141,608566,None,foul,...,0,0,0,0,0,Standard,Standard,195,0.0,-0.049
4052,FF,2021-04-01,95.1,-1.92,6.1,"Márquez, Germán",605141,608566,None,ball,...,0,0,0,0,0,Standard,Standard,<NA>,0.0,0.038

In [8]:
data.columns

Index(['pitch_type', 'game_date', 'release_speed', 'release_pos_x',
       'release_pos_z', 'player_name', 'batter', 'pitcher', 'events',
       'description', 'spin_dir', 'spin_rate_deprecated',
       'break_angle_deprecated', 'break_length_deprecated', 'zone', 'des',
       'game_type', 'stand', 'p_throws', 'home_team', 'away_team', 'type',
       'hit_location', 'bb_type', 'balls', 'strikes', 'game_year', 'pfx_x',
       'pfx_z', 'plate_x', 'plate_z', 'on_3b', 'on_2b', 'on_1b',
       'outs_when_up', 'inning', 'inning_topbot', 'hc_x', 'hc_y',
       'tfs_deprecated', 'tfs_zulu_deprecated', 'fielder_2', 'umpire', 'sv_id',
       'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'sz_top', 'sz_bot',
       'hit_distance_sc', 'launch_speed', 'launch_angle', 'effective_speed',
       'release_spin_rate', 'release_extension', 'game_pk', 'pitcher.1',
       'fielder_2.1', 'fielder_3', 'fielder_4', 'fielder_5', 'fielder_6',
       'fielder_7', 'fielder_8', 'fielder_9', 'release_pos_y',
       'estimated_ba_using_speedangle', 'estimated_woba_using_speedangle',
       'woba_value', 'woba_denom', 'babip_value', 'iso_value',
       'launch_speed_angle', 'at_bat_number', 'pitch_number', 'pitch_name',
       'home_score', 'away_score', 'bat_score', 'fld_score', 'post_away_score',
       'post_home_score', 'post_bat_score', 'post_fld_score',
       'if_fielding_alignment', 'of_fielding_alignment', 'spin_axis',
       'delta_home_win_exp', 'delta_run_exp'],
      dtype='object')

In [9]:
df= data[["game_date","player_name","pitch_type","release_spin_rate"]]
prebandf= preban_data[["game_date","player_name","pitch_type","release_spin_rate"]]
#pull relevant columns from statcast data

In [10]:
standf = pstpitchdata[['Name', 'Age', '#days', 'Lev', 'Tm', 'G', 'GS', 'W', 'L', 'SV', 'IP',
       'H', 'R', 'ER', 'BB', 'SO', 'HR', 'HBP', 'ERA', 'AB', '2B', '3B', 'IBB',
       'GDP', 'SF', 'SB', 'CS', 'PO', 'BF', 'Pit', 'Str', 'StL', 'StS',
       'GB/FB', 'LD', 'PU', 'WHIP', 'BAbip', 'SO9', 'SO/W']]
prestandf = prepitchdata[['Name', 'Age', '#days', 'Lev', 'Tm', 'G', 'GS', 'W', 'L', 'SV', 'IP',
       'H', 'R', 'ER', 'BB', 'SO', 'HR', 'HBP', 'ERA', 'AB', '2B', '3B', 'IBB',
       'GDP', 'SF', 'SB', 'CS', 'PO', 'BF', 'Pit', 'Str', 'StL', 'StS',
       'GB/FB', 'LD', 'PU', 'WHIP', 'BAbip', 'SO9', 'SO/W']]
#Put standard data into dataframes

In [16]:
standf

,Name,Age,#days,Lev,Tm,G,GS,W,L,SV,...,Str,StL,StS,GB/FB,LD,PU,WHIP,BAbip,SO9,SO/W
1,Fernando Abad,35,9,Maj-AL,Baltimore,16,0,NaN,NaN,NaN,...,0.61,0.17,0.06,0.49,0.26,0.06,1.698,0.344,5.1,1.43
2,Cory Abbott,25,9,Maj-NL,Chicago,3,1,NaN,NaN,NaN,...,0.59,0.14,0.06,0.38,0.28,0.03,2.000,0.259,6.0,1.00
3,Albert Abreu,25,9,Maj-AL,New York,24,0,2.0,NaN,1.0,...,0.61,0.16,0.10,0.44,0.25,0.05,1.429,0.243,8.0,1.67
4,Bryan Abreu,24,42,Maj-AL,Houston,10,0,1.0,NaN,NaN,...,0.59,0.14,0.14,0.41,0.29,0.06,1.839,0.394,11.3,2.60
5,Domingo Acevedo,27,7,Maj-AL,Oakland,10,0,NaN,NaN,NaN,...,0.66,0.11,0.14,0.42,0.16,0.06,1.182,0.214,7.4,2.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822,Alex Young,27,28,"Maj-AL,Maj-NL","Cleveland,Arizona",13,1,NaN,2.0,NaN,...,0.61,0.13,0.09,0.46,0.26,0.04,2.431,0.411,5.1,1.00
823,Angel Zerpa,21,10,Maj-AL,Kansas City,1,1,NaN,1.0,NaN,...,0.65,0.21,0.04,0.47,0.33,0.00,0.800,0.214,7.2,4.00
824,Kyle Zimmer,29,8,Maj-AL,Kansas City,29,1,1.0,1.0,NaN,...,0.58,0.15,0.10,0.52,0.16,0.06,1.866,0.316,6.3,0.95
825,Bruce Zimmermann,26,7,Maj-AL,Baltimore,2,2,NaN,1.0,NaN,...,0.63,0.16,0.06,0.33,0.22,0.06,1.929,0.313,5.8,1.50
826,Tyler Zuber,26,10,Maj-AL,Kansas City,11,0,NaN,1.0,NaN,...,0.66,0.14,0.09,0.42,0.30,0.09,1.355,0.300,7.8,4.50

In [17]:
prestandf

,Name,Age,#days,Lev,Tm,G,GS,W,L,SV,...,Str,StL,StS,GB/FB,LD,PU,WHIP,BAbip,SO9,SO/W
1,Cory Abbott,25,113,Maj-NL,Chicago,4,0,NaN,NaN,NaN,...,0.56,0.11,0.09,0.39,0.11,0.18,1.560,0.250,6.5,1.20
2,Albert Abreu,25,134,Maj-AL,New York,4,0,NaN,NaN,NaN,...,0.61,0.20,0.14,0.50,0.11,0.06,0.692,0.059,10.4,2.50
3,Bryan Abreu,24,137,Maj-AL,Houston,21,0,2.0,3.0,1.0,...,0.59,0.13,0.13,0.51,0.14,0.09,1.325,0.269,8.1,1.77
4,Jason Adam,29,154,Maj-NL,Chicago,9,0,NaN,NaN,NaN,...,0.53,0.13,0.13,0.33,0.33,0.17,1.957,0.471,15.3,2.17
5,Austin Adams,30,114,Maj-NL,San Diego,31,0,2.0,1.0,NaN,...,0.61,0.20,0.14,0.40,0.21,0.06,0.960,0.267,13.7,3.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,T.J. Zeuch,25,115,Maj-AL,Toronto,5,3,NaN,2.0,NaN,...,0.63,0.15,0.07,0.49,0.16,0.04,2.000,0.294,4.8,0.89
706,Kyle Zimmer,29,112,Maj-AL,Kansas City,24,1,3.0,NaN,2.0,...,0.62,0.17,0.11,0.52,0.16,0.03,0.940,0.226,9.1,2.55
707,Bruce Zimmermann,26,119,Maj-AL,Baltimore,12,11,4.0,4.0,NaN,...,0.63,0.17,0.11,0.42,0.28,0.08,1.475,0.322,8.0,2.65
708,Jordan Zimmermann,35,156,Maj-NL,Milwaukee,2,0,NaN,NaN,NaN,...,0.61,0.11,0.02,0.52,0.22,0.00,1.765,0.318,0.0,0.00
709,Tyler Zuber,26,128,Maj-AL,Kansas City,20,0,NaN,2.0,NaN,...,0.56,0.15,0.11,0.28,0.26,0.15,1.706,0.250,8.5,1.07

In [11]:
#Rename columns after June 20th to pst_stat
pstdf = standf.rename(columns={'Age':'pst_Age', '#days':'pst_days', 'Lev':'pst_lev', 
                               'Tm':'pst_team', 'G':'pst_G', 'GS':'pst_GS', 'W':'pst_W', 'L':'pst_L', 'SV':'pst_SV', 
                               'IP':'pst_IP',
       'H':'pst_H', 'R':'pst_R', 'ER':'pst_ER', 'BB':'pst_BB', 'SO':'pst_SO', 'HR':'pst_HR', 'HBP':'pst_HBP',
                               'ERA':'pst_ERA', 'AB':'pst_AB', '2B':'pst_2B', '3B':'pst_3B', 'IBB':'pst_IBB',
       'GDP':'pst_GDP','SF':'pst_SF', 'SB':'pst_SB', 'CS':'pst_CS', 'PO':'pst_PO', 'BF':'pst_BF', 'Pit':'pst_Pit',
                               'Str':'pst_Str', 'StL':'pst_StL', 'StS':'pst_StS',
       'GB/FB':'pst_GB/FB', 'LD':'pst_LD', 'PU':'pst_PU', 'WHIP':'pst_WHIP', 'BAbip':'pst_BAbip', 'SO9':'pst_SO9', 'SO/W':'pst_SO/W'})

In [18]:
prestandf

,Name,Age,#days,Lev,Tm,G,GS,W,L,SV,...,Str,StL,StS,GB/FB,LD,PU,WHIP,BAbip,SO9,SO/W
1,Cory Abbott,25,113,Maj-NL,Chicago,4,0,NaN,NaN,NaN,...,0.56,0.11,0.09,0.39,0.11,0.18,1.560,0.250,6.5,1.20
2,Albert Abreu,25,134,Maj-AL,New York,4,0,NaN,NaN,NaN,...,0.61,0.20,0.14,0.50,0.11,0.06,0.692,0.059,10.4,2.50
3,Bryan Abreu,24,137,Maj-AL,Houston,21,0,2.0,3.0,1.0,...,0.59,0.13,0.13,0.51,0.14,0.09,1.325,0.269,8.1,1.77
4,Jason Adam,29,154,Maj-NL,Chicago,9,0,NaN,NaN,NaN,...,0.53,0.13,0.13,0.33,0.33,0.17,1.957,0.471,15.3,2.17
5,Austin Adams,30,114,Maj-NL,San Diego,31,0,2.0,1.0,NaN,...,0.61,0.20,0.14,0.40,0.21,0.06,0.960,0.267,13.7,3.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,T.J. Zeuch,25,115,Maj-AL,Toronto,5,3,NaN,2.0,NaN,...,0.63,0.15,0.07,0.49,0.16,0.04,2.000,0.294,4.8,0.89
706,Kyle Zimmer,29,112,Maj-AL,Kansas City,24,1,3.0,NaN,2.0,...,0.62,0.17,0.11,0.52,0.16,0.03,0.940,0.226,9.1,2.55
707,Bruce Zimmermann,26,119,Maj-AL,Baltimore,12,11,4.0,4.0,NaN,...,0.63,0.17,0.11,0.42,0.28,0.08,1.475,0.322,8.0,2.65
708,Jordan Zimmermann,35,156,Maj-NL,Milwaukee,2,0,NaN,NaN,NaN,...,0.61,0.11,0.02,0.52,0.22,0.00,1.765,0.318,0.0,0.00
709,Tyler Zuber,26,128,Maj-AL,Kansas City,20,0,NaN,2.0,NaN,...,0.56,0.15,0.11,0.28,0.26,0.15,1.706,0.250,8.5,1.07

In [19]:
pstdf

,Name,pst_Age,pst_days,pst_lev,pst_team,pst_G,pst_GS,pst_W,pst_L,pst_SV,...,pst_Str,pst_StL,pst_StS,pst_GB/FB,pst_LD,pst_PU,pst_WHIP,pst_BAbip,pst_SO9,pst_SO/W
1,Fernando Abad,35,9,Maj-AL,Baltimore,16,0,NaN,NaN,NaN,...,0.61,0.17,0.06,0.49,0.26,0.06,1.698,0.344,5.1,1.43
2,Cory Abbott,25,9,Maj-NL,Chicago,3,1,NaN,NaN,NaN,...,0.59,0.14,0.06,0.38,0.28,0.03,2.000,0.259,6.0,1.00
3,Albert Abreu,25,9,Maj-AL,New York,24,0,2.0,NaN,1.0,...,0.61,0.16,0.10,0.44,0.25,0.05,1.429,0.243,8.0,1.67
4,Bryan Abreu,24,42,Maj-AL,Houston,10,0,1.0,NaN,NaN,...,0.59,0.14,0.14,0.41,0.29,0.06,1.839,0.394,11.3,2.60
5,Domingo Acevedo,27,7,Maj-AL,Oakland,10,0,NaN,NaN,NaN,...,0.66,0.11,0.14,0.42,0.16,0.06,1.182,0.214,7.4,2.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822,Alex Young,27,28,"Maj-AL,Maj-NL","Cleveland,Arizona",13,1,NaN,2.0,NaN,...,0.61,0.13,0.09,0.46,0.26,0.04,2.431,0.411,5.1,1.00
823,Angel Zerpa,21,10,Maj-AL,Kansas City,1,1,NaN,1.0,NaN,...,0.65,0.21,0.04,0.47,0.33,0.00,0.800,0.214,7.2,4.00
824,Kyle Zimmer,29,8,Maj-AL,Kansas City,29,1,1.0,1.0,NaN,...,0.58,0.15,0.10,0.52,0.16,0.06,1.866,0.316,6.3,0.95
825,Bruce Zimmermann,26,7,Maj-AL,Baltimore,2,2,NaN,1.0,NaN,...,0.63,0.16,0.06,0.33,0.22,0.06,1.929,0.313,5.8,1.50
826,Tyler Zuber,26,10,Maj-AL,Kansas City,11,0,NaN,1.0,NaN,...,0.66,0.14,0.09,0.42,0.30,0.09,1.355,0.300,7.8,4.50

In [24]:
standardstatsdf = pstdf.merge(prestandf)
#Merge standard stats

In [25]:
standardstatsdf = standardstatsdf.set_index('Name')
#Set index to player name

In [26]:
df['release_spin_rate']=df['release_spin_rate'].astype(float)
prebandf['release_spin_rate']=prebandf['release_spin_rate'].astype(float)
#Set spinrate to float for pivot table purposes

C:\Users\Robby\AppData\Local\Temp/ipykernel_17212/3856247169.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['release_spin_rate']=df['release_spin_rate'].astype(float)
C:\Users\Robby\AppData\Local\Temp/ipykernel_17212/3856247169.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prebandf['release_spin_rate']=prebandf['release_spin_rate'].astype(float)

In [27]:
df3=df.pivot_table(index=['player_name'],values = 'release_spin_rate',columns="pitch_type",aggfunc='mean')
df5=prebandf.pivot_table(index=['player_name'],values = 'release_spin_rate',columns="pitch_type",aggfunc='mean')
# Get average spin rates per pitcher

In [28]:
df3 = df3[['FF']]
df5 = df5[['FF']]
#Only fastballs

In [29]:
df3 = df3.rename(columns={'FF':'PostB FF'})
df5 = df5.rename(columns={'FF':'PreB FF'})
#Rename to post and pre ban

In [30]:
print(df3)
print(df5)

pitch_type            PostB FF
player_name
Abad, Fernando     2112.111111
Abbott, Cory       2300.324074
Abreu, Albert      2122.200000
Abreu, Bryan       2186.699029
Acevedo, Domingo   2065.931818
...                        ...
Zimmermann, Bruce  2317.102564
Zuber, Tyler       2253.827160
de Geus, Brett     1909.166667
deGrom, Jacob      2385.443038
Álvarez, José      2200.548387

[794 rows x 1 columns]
pitch_type              PreB FF
player_name
Abbott, Cory        2341.202020
Abreu, Albert       2159.535714
Abreu, Bryan        2228.729469
Adam, Jason         2607.864078
Adams, Austin       2641.583333
...                         ...
Zimmermann, Jordan  2391.571429
Zuber, Tyler        2221.995283
de Geus, Brett      2280.666667
deGrom, Jacob       2427.282051
Álvarez, José       2337.329545

[683 rows x 1 columns]

In [31]:
spindf = df3.join(df5)
#join post and pre spin
spindf.index

Index(['Abad, Fernando', 'Abbott, Cory', 'Abreu, Albert', 'Abreu, Bryan',
       'Acevedo, Domingo', 'Adam, Jason', 'Adams, Austin', 'Adon, Joan',
       'Aguilar, Miguel', 'Akin, Keegan',
       ...
       'Yarbrough, Ryan', 'Ynoa, Huascar', 'Young, Alex', 'Zerpa, Angel',
       'Zimmer, Kyle', 'Zimmermann, Bruce', 'Zuber, Tyler', 'de Geus, Brett',
       'deGrom, Jacob', 'Álvarez, José'],
      dtype='object', name='player_name', length=794)

In [32]:
spindf = spindf.dropna()

In [33]:
namelist = spindf.index
[n.split(", ") for n in namelist]
[n.split(", ")[::-1] for n in namelist]
namelist = [" ".join(n.split(", ")[::-1]) for n in namelist]
#Edit names to max index of Standard Stats

In [34]:
spindf.index = namelist
#Assign index to new names

In [35]:
df = standardstatsdf.join(spindf)
df
#join indexs

,pst_Age,pst_days,pst_lev,pst_team,pst_G,pst_GS,pst_W,pst_L,pst_SV,pst_IP,...,StS,GB/FB,LD,PU,WHIP,BAbip,SO9,SO/W,PostB FF,PreB FF
A.J. Minter,27,8,Maj-NL,Atlanta,31,0,2.0,4.0,NaN,27.1,...,0.14,0.44,0.20,0.11,1.320,0.309,10.4,2.90,2345.961905,2357.496894
A.J. Puk,26,33,Maj-AL,Oakland,11,0,NaN,3.0,NaN,10.0,...,0.09,0.57,0.14,0.00,1.200,0.143,10.8,1.33,2189.645161,2259.722222
Aaron Bummer,27,8,Maj-AL,Chicago,34,0,5.0,1.0,NaN,30.2,...,0.14,0.77,0.11,0.02,1.538,0.359,12.8,2.38,NaN,NaN
Aaron Civale,26,7,Maj-AL,Cleveland,7,7,2.0,3.0,NaN,31.1,...,0.10,0.46,0.25,0.07,1.065,0.248,6.9,3.38,2374.925000,2316.467236
Aaron Loup,33,11,Maj-NL,New York,40,2,4.0,NaN,NaN,37.0,...,0.13,0.52,0.35,0.04,1.068,0.346,11.0,8.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zack Burdi,26,34,Maj-AL,"Chicago,Baltimore",4,0,NaN,NaN,NaN,5.0,...,0.16,0.35,0.15,0.20,1.667,0.263,6.0,1.00,2632.693878,2512.627451
Zack Godley,31,112,Maj-NL,Milwaukee,1,0,NaN,NaN,NaN,0.1,...,0.13,0.30,0.30,0.00,2.700,0.286,13.5,1.00,2134.500000,2158.875000
Zack Greinke,37,7,Maj-AL,Houston,15,14,4.0,4.0,NaN,79.2,...,0.09,0.43,0.25,0.07,1.139,0.273,6.5,3.47,2214.516060,2251.051510
Zack Littell,25,8,Maj-NL,San Francisco,40,0,4.0,NaN,2.0,41.2,...,0.12,0.61,0.11,0.03,1.286,0.271,6.9,1.78,2079.380048,2020.769697
Zack Wheeler,31,12,Maj-NL,Philadelphia,18,18,9.0,7.0,NaN,117.0,...,0.14,0.49,0.20,0.11,0.934,0.276,11.0,5.36,2385.919246,2390.238636

In [41]:
df.to_csv('2021StandardPrePost&FastballSpin.csv')
#print to csv